name: Build Middleware
description: Builds Middleware app docker image
inputs:
  project_name:
    description: 'Project name'
    required: true
  docker_registry_url:
    description: 'Docker registry url'
    required: false
    default: "registry.storefrontcloud.io"
  docker_registry_ref:
    description: "Docker registry reference"
    required: true
  cloud_username:
    description: 'Cloud username'
    required: true
  cloud_password:
    description: 'Cloud password'
    required: true
  npm_email:
    description: 'NPM email'
    required: true
  npm_pass:
    description: 'NPM password'
    required: true
  npm_user:
    description: 'NPM user'
    required: true
  npm_registry:
    description: 'NPM registry'
    required: false
    default: 'https://registrynpm.storefrontcloud.io'
  version:
    description: 'Version of the app'
    required: true

runs:
  using: "composite"
  steps:
    # Need buildx for caching
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login Alokai Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry_url }}
        username: ${{ inputs.npm_user }}
        password: ${{ inputs.npm_pass }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .vuestorefrontcloud/docker/middleware/Dockerfile-middleware
        push: true
        tags: ${{ inputs.docker_registry_ref }}/vue-storefront-middleware:${{ inputs.version }}
        # Inline cache
        cache-from: "type=registry,ref=${{ inputs.docker_registry_ref }}/vue-storefront-middleware:${{ inputs.project_name }}-buildcache"
        cache-to: "type=registry,ref=${{ inputs.docker_registry_ref }}/vue-storefront-middleware:${{ inputs.project_name }}-buildcache,mode=max"
        build-args: |
          NPM_EMAIL=${{ inputs.npm_email }}
          NPM_PASS=${{ inputs.npm_pass }}
          NPM_USER=${{ inputs.npm_user }}
          NPM_REGISTRY=https://registrynpm.storefrontcloud.io
      env:
        NPM_EMAIL: ${{ inputs.npm_email }}
        NPM_PASS: ${{ inputs.npm_pass }}
        NPM_USER: ${{ inputs.npm_user }}
        NPM_REGISTRY: https://registrynpm.storefrontcloud.io

