name: Build Middleware
description: Builds Middleware app docker image
inputs:
  project_name:
    description: 'Project name'
    required: true
  docker_registry_url:
    description: 'Docker registry url'
    required: false
    default: 'registry.vuestorefront.cloud'
  cloud_username:
    description: 'Cloud username'
    required: true
  cloud_password:
    description: 'Cloud password'
    required: true
  npm_email:
    description: 'NPM email'
    required: true
  npm_pass:
    description: 'NPM password'
    required: true
  npm_user:
    description: 'NPM user'
    required: true
  npm_registry:
    description: 'NPM registry'
    required: false
    default: 'https://registrynpm.storefrontcloud.io'
  version:
    description: 'Version of the app'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry_url }}
        username: ${{ inputs.cloud_username }}
        password: ${{ inputs.cloud_password }}

    - name: Resolve values of the versions, docker ref & dockerfile path
      id: resolve
      shell: bash
      run: |
        echo "version=${{ inputs.version || github.sha }}" >> $GITHUB_OUTPUT
        echo "ref=${{ inputs.docker_registry_url }}/${{ inputs.project_name }}-storefrontcloud-io" >> $GITHUB_OUTPUT

    - name: Check for existing image
      id: check-existing-image
      uses: javajawa/check-registry-for-image@v2
      with:
        registry: ${{ inputs.docker_registry_url }}
        repository: ${{ inputs.project_name }}-storefrontcloud-io/vue-storefront-middleware
        tag: ${{ steps.resolve.outputs.version }}

    - name: Build and publish docker image
      uses: docker/build-push-action@v6
      if: ${{ steps.check-existing-image.outputs.exists == 'false' }}
      with:
        context: .
        file: .vuestorefrontcloud/docker/middleware/Dockerfile-middleware
        push: true
        tags: ${{ steps.resolve.outputs.ref }}/vue-storefront-middleware:${{ steps.resolve.outputs.version }}
        cache-from: "type=registry,ref=${{ steps.resolve.outputs.ref }}/vue-storefront-middleware:buildcache"
        cache-to: "type=registry,ref=${{ steps.resolve.outputs.ref }}/vue-storefront-middleware:buildcache,mode=max"
        build-args: |
          NPM_EMAIL=${{ inputs.npm_email }}
          NPM_PASS=${{ inputs.npm_pass }}
          NPM_USER=${{ inputs.npm_user }}
          NPM_REGISTRY=${{ inputs.npm_registry }}
