name: Build Frontend
description: Builds Storefront app docker image
inputs:
  frontend:
    description: 'Switch between Next.js and Nuxt'
    required: false
    default: 'next'
  project_name:
    description: 'Project name'
    required: true
  docker_registry_url:
    description: 'Docker registry url'
    required: false
    default: 'registry.vuestorefront.cloud'
  cloud_username:
    description: 'Cloud username'
    required: true
  cloud_password:
    description: 'Cloud password'
    required: true
  npm_email:
    description: 'NPM email'
    required: true
  npm_pass:
    description: 'NPM password'
    required: true
  npm_user:
    description: 'NPM user'
    required: true
  npm_registry:
    description: 'NPM registry'
    required: false
    default: 'https://registrynpm.storefrontcloud.io'
  version:
    description: 'Version of the app'
    required: false
  image_provider:
    description: 'Image provider (only for Nuxt)'
    required: false
    default: 'ipx'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry_url }}
        username: ${{ inputs.cloud_username }}
        password: ${{ inputs.cloud_password }}

    - name: Resolve values of the versions, docker ref & dockerfile path
      id: resolve
      shell: bash
      run: |
        # Set the version of the app based on user input or use git commit hash
        echo "version=${{ inputs.version || github.sha }}" >> $GITHUB_OUTPUT
        # Set the reference address for app in docker registry
        echo "ref=${{ inputs.docker_registry_url }}/${{ inputs.project_name }}-storefrontcloud-io" >> $GITHUB_OUTPUT
        # Set the path to the Dockerfile base on selected frontend framework
        if [[ $FRONTEND == "next" ]]; then
          echo "path=.vuestorefrontcloud/docker/nextjs/Dockerfile-frontend" >> $GITHUB_OUTPUT
        elif [[ $FRONTEND == "nextjs" ]]; then
          echo "path=.vuestorefrontcloud/docker/nextjs/Dockerfile-frontend" >> $GITHUB_OUTPUT
        elif [[ $FRONTEND == "nuxt" ]]; then
          echo "path=.vuestorefrontcloud/docker/nuxtjs/Dockerfile-frontend" >> $GITHUB_OUTPUT
        else
          echo "Error: Unsupported FRONTEND value. Valid options are 'next' or 'nuxt'."
          exit 1
        fi
      env:
        FRONTEND: ${{ inputs.frontend }}

    - name: Check for existing image
      id: check-existing-image
      uses: javajawa/check-registry-for-image@v2
      with:
        registry: ${{ inputs.docker_registry_url }}
        repository: ${{ inputs.project_name }}-storefrontcloud-io/vue-storefront
        tag: ${{ steps.resolve.outputs.version }}

    - name: Build and publish docker image
      uses: docker/build-push-action@v6
      if: ${{ steps.check-existing-image.outputs.exists == 'false' }}
      with:
        context: .
        file: ${{ steps.resolve.outputs.path }}
        push: true
        tags: ${{ steps.resolve.outputs.ref }}/vue-storefront:${{ steps.resolve.outputs.version }}
        cache-from: "type=registry,ref=${{ steps.resolve.outputs.ref }}/vue-storefront:buildcache"
        cache-to: "type=registry,ref=${{ steps.resolve.outputs.ref }}/vue-storefront:buildcache,mode=max"
        build-args: |
          NPM_EMAIL=${{ inputs.npm_email }}
          NPM_PASS=${{ inputs.npm_pass }}
          NPM_USER=${{ inputs.npm_user }}
          NPM_REGISTRY=${{ inputs.npm_registry }}
          NUXT_IMAGE_PROVIDER=${{ inputs.image_provider }}
