name: Build Frontend
description: Builds Storefront app docker image
inputs:
  frontend:
    description: 'Switch between Next.js and Nuxt'
    required: false
    default: 'next'
  project_name:
    description: 'Project name'
    required: true
  docker_registry_url:
    description: 'Docker registry url'
    required: false
    default: 'registry.vuestorefront.cloud'
  cloud_username:
    description: 'Cloud username'
    required: true
  cloud_password:
    description: 'Cloud password'
    required: true
  cloud_region:
    description: 'Cloud region'
    required: true
  npm_email:
    description: 'NPM email'
    required: true
  npm_pass:
    description: 'NPM password'
    required: true
  npm_user:
    description: 'NPM user'
    required: true
  npm_registry:
    description: 'NPM registry'
    required: false
    default: 'https://registrynpm.storefrontcloud.io'
  api_base_url:
    description: 'Base Middleware API URL for Storefront. By default https://project_name.region.gcp.storefrontcloud.io/api'
    required: false
  multistore_enabled:
    description: 'Switch for multistore'
    required: false
    default: 'false'
  image_provider:
    description: 'Image provider name'
    required: false
  image_provider_upload_url:
    description: 'Image Provider upload url'
    required: false
  image_provider_fetch_url:
    description: 'Image Provider fetch url'
    required: false
  coveo_organization_id:
    description: 'Coveo organization id'
    required: false
  coveo_access_token:
    description: 'Coveo access token'
    required: false
  version:
    description: 'Version of the app'
    required: false
  default_html_cache_control:
    description: 'Default cache control header value for SSR pages'
    required: false
    default: 'public, max-age=0, s-maxage=15, must-revalidate'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Set dynamic NEXT_PUBLIC_* environment variables
      id: set-public-env-vars-next
      if: ${{ inputs.frontend == 'next' || inputs.frontend == 'nextjs' }}
      shell: bash
      run: |
        # Collect all NEXT_PUBLIC_* variables
        NEXT_PUBLIC_VARS=$(printenv | grep '^NEXT_PUBLIC_' | awk -F= '{print "--build-arg " $1 "=" $2}' | tr '\n' ' ')
        # Collect all PUBLIC_* variables and transform them to NEXT_PUBLIC_*
        NEXT_PUBLIC_VARS_TRANSFORMED=$(printenv | grep '^PUBLIC_' | awk -F= '{print "--build-arg NEXT_" $1 "=" $2}' | tr '\n' ' ')
        # Combine both sets of variables
        PUBLIC_VARS="$NEXT_PUBLIC_VARS $NEXT_PUBLIC_VARS_TRANSFORMED"
        echo "PUBLIC_VARS=$PUBLIC_VARS" >> $GITHUB_ENV
    - name: Set dynamic NUXT_PUBLIC_* environment variables
      id: set-public-env-vars-nuxt
      if: ${{ inputs.frontend == 'nuxt' }}
      shell: bash
      run: |
        # Collect all NUXT_PUBLIC_* variables
        NEXT_PUBLIC_VARS=$(printenv | grep '^NUXT_PUBLIC_' | awk -F= '{print "--build-arg " $1 "=" $2}' | tr '\n' ' ')
        # Collect all PUBLIC_* variables and transform them to NUXT_PUBLIC_*
        NEXT_PUBLIC_VARS_TRANSFORMED=$(printenv | grep '^PUBLIC_' | awk -F= '{print "--build-arg NUXT_" $1 "=" $2}' | tr '\n' ' ')
        # Combine both sets of variables
        PUBLIC_VARS="$NEXT_PUBLIC_VARS $NEXT_PUBLIC_VARS_TRANSFORMED"
        echo "PUBLIC_VARS=$PUBLIC_VARS" >> $GITHUB_ENV
    - name: Build and publish docker image (Next.js frontend)
      if: ${{ inputs.frontend == 'next' || inputs.frontend == 'nextjs' }}
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ inputs.project_name }}-storefrontcloud-io/vue-storefront:${{ inputs.version || github.sha }}
        registry: ${{ inputs.docker_registry_url }}
        username: ${{ inputs.cloud_username }}
        password: ${{ inputs.cloud_password }}
        dockerfile: .vuestorefrontcloud/docker/nextjs/Dockerfile-frontend
        buildoptions: --compress
        buildargs: |
          NPM_EMAIL=${{ inputs.npm_email }}
          NPM_PASS=${{ inputs.npm_pass }}
          NPM_USER=${{ inputs.npm_user }}
          NPM_REGISTRY=${{ inputs.npm_registry }}
          NEXT_IMAGE_PROVIDER=${{ inputs.image_provider }}
          NEXT_DEFAULT_HTML_CACHE_CONTROL=${{ inputs.default_html_cache_control }}
          ${{ env.PUBLIC_VARS }}
    - name: Build and publish docker image (Nuxt frontend)
      if: ${{ inputs.frontend == 'nuxt' }}
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ inputs.project_name }}-storefrontcloud-io/vue-storefront:${{ inputs.version || github.sha }}
        registry: ${{ inputs.docker_registry_url }}
        username: ${{ inputs.cloud_username }}
        password: ${{ inputs.cloud_password }}
        dockerfile: .vuestorefrontcloud/docker/nuxtjs/Dockerfile-frontend
        buildoptions: --compress
        buildargs: |
          NPM_EMAIL=${{ inputs.npm_email }}
          NPM_PASS=${{ inputs.npm_pass }}
          NPM_USER=${{ inputs.npm_user }}
          NPM_REGISTRY=${{ inputs.npm_registry }}
          NUXT_IMAGE_PROVIDER=${{ inputs.image_provider }}
          NUXT_DEFAULT_HTML_CACHE_CONTROL=${{ inputs.default_html_cache_control }}
          ${{ env.PUBLIC_VARS }}
